[package]
name = "lazytool"
version = "0.1.4"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["wxnacy@gmail.com"]
description = "Rust lazy toolkit"
repository = "https://github.com/wxnacy/lazytool"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
chrono-tz = "0.10.0"
regex = "1.11.1"
