[package]
name = "lazytool"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["wxnacy@gmail.com"]
description = "Rust lazy toolkit"
repository = "https://github.com/wxnacy/lazytool"

[dependencies]
